# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mishop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  mail:
    host: smtp.qq.com
    username: 3222494855@qq.com
    password: xnfjtvgrqgzodahh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo
